lab_config:
  k8s_version: '1.33.2-1.1'
  containerd_version: '1.7.27-1'
  cilium_version: '1.17.6'
  worker_nodes: 3
  lab_name: 'Advanced-K8s-Lab'
  network_prefix: '192.168.20'
  pod_cidr: '172.30.0.0/16'
  box_image: "bento/ubuntu-24.04"
  box_version: "202502.21.0"
